### ISSUE TITLE
Properties ignored in the translation XML to RDL

### ISSUE THREAD

**Issue by MarinaQT** [SystemRDL/PeakRDL#25] opened 2023-05-31 08:42 UTC
Hello dear PeakRDL developers

First of all, thanks a lot for the cool project and package. Started using it last week, and having helpful results!
Nevertheless having some difficulties, for example:

1) XML => RDL
while translating  XML (ipxact 2009)  to RDL, certain properties are ignored, like: 
for registers:    hdl_path
for register-files:  range and width
The register-file properties are ignored, but then if convert back RDL=>XML some kind of default value is taken...

2) RDL => XML
Here also the hdl_path property is ignored, when translating back into XML.
So overall if hdl_path property supported?

3) XML version
then tried newer version of XML (ipxact 2014, converted with xsltproc and official stylesheet from accelera), but here the parsing in peakrdl crashes (error below)
    d['reset.value'] = self.parse_integer(get_text(value_el))
  File "/home/mdqe/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/peakrdl_ipxact/importer.py", line 691, in parse_integer
    raise ValueError

Are any of these limitations/issues already known? Any workaround available?

**Comment by MarinaQT** [comment] 2023-05-31 09:49
Did a further trial about the hdl_path property:
When declared in XML or RDL, peakrdl takes it into account for generation of the UVM pkg.
But it is not translating it when transforming input formats (from XML to RDL, and vice versa).

**Comment by amykyta3** [comment] 2023-06-01 04:09
IP-XACT conversion is not going to be 100% symmetrical. A good amount of features between IP-XACT and SystemRDL do indeed overlap, but not all, so some information loss will happen in the conversion. The PeakRDL projects are optimized to use SystemRDL concepts, so I'll always recommend using those.

Regarding HDL paths, see this issue ticket: https://github.com/SystemRDL/PeakRDL-ipxact/issues/14
The feature overlap is a little clunky, and SystemRDL's definition of HDL paths is a little sloppy.

Regarding range/width, this is due to a difference in philosophy between IP-XACT and SystemRDL standards. IP-XACT lets you define an explicit block size, where SystemRDL does not have a mechanism to explicitly add address padding (it can only be implied by instance placement). For this reason, you might get subtle differences (see my first comment on symmetry above)

For the ValueError exception, can you attach a small example XML file so I can reproduce the issue? The importer should be able to handle all variants of IP-XACT, including all variations of integer representations.

**Comment by MarinaQT** [comment] 2023-06-01 15:17
Thanks a lot for quick answer. 
Please find below an example of a GenericBlock XML files in three ipxact versions: 1.5, 2009 and 2014
As commented above 1.5 and 2009 can be read into peakrdl (for example for dump) and 2014 fails.
[GenericBlock.zip](https://github.com/SystemRDL/PeakRDL/files/11626907/GenericBlock.zip)

**Comment by MarinaQT** [comment] 2023-06-01 15:28
Another question please:
currently installed peakrdl inside a PyCharm project, which is running very smoothly.
For future usage, would like to install outside PyCharm, with pip install directly in the Linux command shell. 
According to the documentation, it seems this is possible if Linux environment has python3 w/ version 3.6 or above (we have version 3.6.8). So have tried with following steps:
1)  Created a venv and activated it
2) Then called setup.py provided in the peakrdl package download
But the installation failed with message below. Can you provide any debug hints? Thanks for your attention!!
PS.: perhaps you prefer to take this question on a separated issue... sorry
===================== ERROR MSG ==========================
Traceback (most recent call last): ....
  File "/tmp/mdqe/projects/Sandbox/work-Top/data/ralgen_trial2/peakrdl-0.8.0/tutorial_env/bin/peakrdl", line 11, in <module>
    load_entry_point('peakrdl==0.8.0', 'console_scripts', 'peakrdl')()
...
File "/tmp/mdqe/projects/Sandbox/work-Top/data/ralgen_trial2/peakrdl-0.8.0/tutorial_env/lib64/python3.6/site-packages/tomli-2.0.1-py3.6.egg/tomli/_parser.py", line 5
    from __future__ import annotations

**Comment by amykyta3** [comment] 2023-06-01 15:44
Ah i see the issue with the 2014 xml. It looks like the tool you are using is generating values that have expressions in them:
```
              <ipxact:reset>
                <ipxact:value>('hABCD) / $pow(2,0) % $pow(2,8)</ipxact:value>
                <ipxact:mask>('hffff) / $pow(2,0) % $pow(2,8)</ipxact:mask>
              </ipxact:reset>
```

Currently the importer assumes simple integer literals.
Should be possible to extend support for some simple constant expressions like this.

Regarding the install issue - i have not seen that before. Will have to look into it in more detail.

**Comment by amykyta3** [comment] 2023-06-06 03:09
Here is an example in the HTML generator's readme file: https://github.com/SystemRDL/PeakRDL-html#peakrdl-toml-config-options

I admit I need to improve how the PeakRDL documentation links to all the sub-component documentation. It isn't the most obvious.

**Comment by amykyta3** [comment] 2023-06-08 04:01
Created this issue to track the expression parsing feature: https://github.com/SystemRDL/PeakRDL-ipxact/issues/18

Since it sounds like everything else we discussed has been answered, I'm closing this.
Feel free to report other issues as you find them. Thanks for all your feedback!

**Closed by amykyta3** 2023-06-08 04:01 UTC

**Comment by MarinaQT** [comment] 2023-06-08 07:01
Hello Alex

thanks for the support, and will follow the expression-parsing issue.

Need to ask you about the installation issue mentioned above.  
Could you have a look on it? Should we track it with a separated issue thread?
